# THIS NOTEBOOK CONTAINS ALL THE REGRESSIONS MODEL TO TEST WHICH IS THE BEST FOR THESE DATA

**STARTING WITH THE MULTIPLE LINEAR REGRESSION**

Importing the Libraries

In [66]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [67]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Splinting the training and test set

In [68]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## **MULTIPLE LINEAR REGRESSION**

In [69]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

# Predicting the result

In [70]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1, 1)),1))

[[431.23 431.43]
 [460.01 458.56]
 [461.14 462.75]
 ...
 [473.26 469.52]
 [438.   442.42]
 [463.28 461.88]]


*# Evaluating the Multiple regression performance*

In [71]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9325315554761303

## **POLYNOMIAL REGRESSION**

In [72]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly = PolynomialFeatures(degree=4)
x_poly = poly.fit_transform(x_train)
regressor = LinearRegression()
regressor.fit(x_poly, y_train)

LinearRegression()

# Predicting the result

In [73]:
y_pred = regressor.predict(poly.fit_transform(x_test))
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1
                                                          )), 1))

[[431.23 433.94]
 [460.01 457.9 ]
 [461.14 460.52]
 ...
 [473.26 469.53]
 [438.   438.27]
 [463.28 461.66]]


## ***Evaluating the performance***

In [74]:
r2_score(y_test, y_pred)

0.945819248451021

# **SUPPORT VECTOR REGRESSION**

In [75]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
svr_x_train = sc_x.fit_transform(x_train)
svr_y_train = sc_y.fit_transform(y_train.reshape(-1, 1))
svr_x_test = sc_x.fit_transform(x_test)

# Training the model

In [76]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(svr_x_train, svr_y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

# Predicting the result

In [77]:
y_pred = sc_y.inverse_transform(regressor.predict(svr_x_test).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), 1))

[[431.23 434.5 ]
 [460.01 457.71]
 [461.14 460.85]
 ...
 [473.26 470.22]
 [438.   439.29]
 [463.28 460.43]]


# ***Evaluating the model performance***

In [78]:
r2_score(y_test, y_pred)

0.9483693304317924

# RANDOM FOREST REGRESSION

In [79]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state=0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

# Predicting the result

In [80]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), 1))

[[431.23 434.05]
 [460.01 458.79]
 [461.14 463.02]
 ...
 [473.26 469.48]
 [438.   439.57]
 [463.28 460.38]]


# *** Evaluating the model performance***

In [82]:
r2_score(y_test, y_pred)

0.9615908334363876

# **Thanks GOD for the first section, the random forest regression is winner**

# Now let look forward for classfication☺☺☺